#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
/**
 * Get a crawler started
 * @var Crawler
 */
$crawler = new Crawler\Reaver;
/**
 * Let's get his party started.
 */
$crawler->crawl();

