#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Database\Schema\Blueprint;

if(isset($argv[1])) {
	if(!checkUrl($argv[1])) {
		if($argv[1] == '--drop-db') {

			$capsule = new Capsule;

			$capsule->addConnection([
			    'driver'    => 'mysql',
			    'host'      => '127.0.0.1',
			    'database'  => 'reaver_db',
			    'username'  => 'homestead',
			    'password'  => 'secret',
			    'charset'   => 'utf8',
			    'collation' => 'utf8_unicode_ci',
			    'prefix'    => '',
			    'port'		=> 33060
			]);

			// Make this Capsule instance available globally via static methods
			$capsule->setAsGlobal();

			// Setup the Eloquent ORM
			$capsule->bootEloquent();
			$capsule->schema()->drop('sites');
			die('Dropping database'.PHP_EOL);
		}

	}
}



/**
 * Get a crawler started
 * @var Crawler
 */
$crawler = new Crawler\Reaver;
/**
 * Let's get his party started.
 */

if(isset($argv[1])) {
	$crawler->setUrl($argv[1]);
}


$crawler->fetch();

$crawler->run();
