#!/usr/bin/env php
<?php

if(!function_exists('readline')) :

    function readline($prompt = null)
    {
        if($prompt)
            echo $prompt;

        $fp = fopen("php://stdin","r");

        $line = rtrim(fgets($fp, 1024));

        return $line;
    }

endif;

$env = false;

if(!file_exists('.env')) 
	file_put_contents('.env', '');
else
	$env = true;


$seed = readline("Please enter a url to start crawling: \n");


$m = new \MongoClient(); // connect

$db = $m->reaver_index;

$index = $db->index;

$date = new \MongoDate();

$site = [
	'url' => $seed, 
	'status' => 'Empty', 
	'expires' => $date, 
	'data' => 'No Data', 
	'created_at'=> $date, 
	'updated_at'=> $date
];

$index->update(['url' => $site['url']], $site, ['upsert' => true]);

if(!file_exists('vendor')) 
	exec('composer install');

exec('composer dump-auto -o');

var_dump($index->findOne($site));